; Lop ears, AKG format, v1.0.

; Generated by Arkos Tracker 3.

Start
StartDisarkGenerateExternalLabel
DisarkByteRegionStart0
    db "AT30"
DisarkPointerRegionStart1
    dw ArpeggioTable    ; The address of the Arpeggio table.
    dw PitchTable    ; The address of the Pitch table.
    dw InstrumentTable    ; The address of the Instrument table.
    dw EffectBlockTable    ; The address of the Effect Block table.
DisarkPointerRegionEnd1


; The addresses of each Subsong.
DisarkPointerRegionStart2
    dw Subsong0_Start
DisarkPointerRegionEnd2

; Declares all the Arpeggios.
ArpeggioTable
DisarkPointerRegionStart3
    dw Arpeggio1
    dw Arpeggio2
DisarkPointerRegionEnd3
Arpeggio1
    db 1    ; The speed.

    db -12
    db 0
    db -128
DisarkWordForceReference4
    dw Arpeggio1 + 1 + 1    ; Loop.

Arpeggio2
    db 4    ; The speed.

    db 0
    db 4
    db 7
    db -128
DisarkWordForceReference5
    dw Arpeggio2 + 0 + 1    ; Loop.


; Declares all the Pitches.
PitchTable
DisarkPointerRegionStart6
    dw Pitch1
DisarkPointerRegionEnd6
Pitch1
    db 1    ; The speed.

    dw 0
Pitch1_GotoNextForLine0
DisarkWordForceReference7
    dw Pitch1_GotoNextForLine0 + 2
    dw 0
Pitch1_GotoNextForLine1
DisarkWordForceReference8
    dw Pitch1_GotoNextForLine1 + 2
    dw 0
Pitch1_GotoNextForLine2
DisarkWordForceReference9
    dw Pitch1_GotoNextForLine2 + 2
    dw 0
Pitch1_GotoNextForLine3
DisarkWordForceReference10
    dw Pitch1_GotoNextForLine3 + 2
    dw 0
Pitch1_GotoNextForLine4
DisarkWordForceReference11
    dw Pitch1_GotoNextForLine4 + 2
    dw 0
Pitch1_GotoNextForLine5
DisarkWordForceReference12
    dw Pitch1_GotoNextForLine5 + 2
    dw 0
Pitch1_GotoNextForLine6
DisarkWordForceReference13
    dw Pitch1_GotoNextForLine6 + 2
    dw 0
Pitch1_GotoNextForLine7
DisarkWordForceReference14
    dw Pitch1_GotoNextForLine7 + 2
    dw 0
Pitch1_GotoNextForLine8
DisarkWordForceReference15
    dw Pitch1_GotoNextForLine8 + 2
    dw -1
Pitch1_GotoNextForLine9
DisarkWordForceReference16
    dw Pitch1_GotoNextForLine9 + 2
    dw -2
Pitch1_GotoNextForLine10
DisarkWordForceReference17
    dw Pitch1_GotoNextForLine10 + 2
    dw -1
Pitch1_GotoNextForLine11
DisarkWordForceReference18
    dw Pitch1_GotoNextForLine11 + 2
    dw 0
Pitch1_GotoNextForLine12
DisarkWordForceReference19
    dw Pitch1_GotoNextForLine12 + 2
    dw 1
Pitch1_GotoNextForLine13
DisarkWordForceReference20
    dw Pitch1_GotoNextForLine13 + 2
    dw 2
Pitch1_GotoNextForLine14
DisarkWordForceReference21
    dw Pitch1_GotoNextForLine14 + 2
    dw 3
Pitch1_GotoNextForLine15
DisarkWordForceReference22
    dw Pitch1_GotoNextForLine15 + 2
    dw 4
Pitch1_GotoNextForLine16
DisarkWordForceReference23
    dw Pitch1_GotoNextForLine16 + 2
    dw 3
Pitch1_GotoNextForLine17
DisarkWordForceReference24
    dw Pitch1_GotoNextForLine17 + 2
    dw 2
Pitch1_GotoNextForLine18
DisarkWordForceReference25
    dw Pitch1_GotoNextForLine18 + 2
    dw 1
DisarkWordForceReference26
    dw Pitch1 + 4 * 8 + 1


; Declares all the Instruments.
InstrumentTable
DisarkPointerRegionStart27
    dw EmptyInstrument
    dw Instrument1
    dw Instrument2
    dw Instrument3
    dw Instrument4
    dw Instrument5
    dw Instrument6
DisarkPointerRegionEnd27

EmptyInstrument
    db 0    ; The speed (>0, 0 for 256).

    db 0    ; No Soft no Hard. Volume: 0. Noise? false.

    db 6    ; Loop to silence.

Instrument1
    db 4    ; The speed (>0, 0 for 256).

    db 249    ; Soft only. Volume: 15. Volume only.

    db 241    ; Soft only. Volume: 14. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 225    ; Soft only. Volume: 12. Volume only.

    db 225    ; Soft only. Volume: 12. Volume only.

    db 225    ; Soft only. Volume: 12. Volume only.

    db 217    ; Soft only. Volume: 11. Volume only.

    db 209    ; Soft only. Volume: 10. Volume only.

    db 201    ; Soft only. Volume: 9. Volume only.

    db 193    ; Soft only. Volume: 8. Volume only.

    db 185    ; Soft only. Volume: 7. Volume only.

    db 177    ; Soft only. Volume: 6. Volume only.

    db 169    ; Soft only. Volume: 5. Volume only.

    db 161    ; Soft only. Volume: 4. Volume only.

    db 153    ; Soft only. Volume: 3. Volume only.

    db 16    ; No Soft no Hard. Volume: 2. Noise? false.

    db 8    ; No Soft no Hard. Volume: 1. Noise? false.

    db 6    ; Loop to silence.

Instrument2
    db 1    ; The speed (>0, 0 for 256).

    db 225    ; Soft only. Volume: 12. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

Instrument2_Loop
    db 225    ; Soft only. Volume: 12. Volume only.

    db 7    ; Loop.
DisarkWordForceReference28
    dw Instrument2_Loop    ; Loop here.

Instrument3
    db 1    ; The speed (>0, 0 for 256).

    db 177    ; Soft only. Volume: 6. Volume only.

    db 193    ; Soft only. Volume: 8. Volume only.

    db 209    ; Soft only. Volume: 10. Volume only.

    db 225    ; Soft only. Volume: 12. Volume only.

    db 241    ; Soft only. Volume: 14. Volume only.

    db 249    ; Soft only. Volume: 15. Volume only.

    db 249    ; Soft only. Volume: 15. Volume only.

    db 249    ; Soft only. Volume: 15. Volume only.

    db 249    ; Soft only. Volume: 15. Volume only.

    db 241    ; Soft only. Volume: 14. Volume only.

    db 241    ; Soft only. Volume: 14. Volume only.

    db 241    ; Soft only. Volume: 14. Volume only.

    db 241    ; Soft only. Volume: 14. Volume only.

    db 241    ; Soft only. Volume: 14. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

Instrument3_Loop
    db 225    ; Soft only. Volume: 12. Volume only.

    db 7    ; Loop.
DisarkWordForceReference29
    dw Instrument3_Loop    ; Loop here.

Instrument4
    db 1    ; The speed (>0, 0 for 256).

    db 225    ; Soft only. Volume: 12. Volume only.

    db 241    ; Soft only. Volume: 14. Volume only.

    db 249    ; Soft only. Volume: 15. Volume only.

    db 249    ; Soft only. Volume: 15. Volume only.

    db 249    ; Soft only. Volume: 15. Volume only.

    db 249    ; Soft only. Volume: 15. Volume only.

    db 241    ; Soft only. Volume: 14. Volume only.

    db 241    ; Soft only. Volume: 14. Volume only.

    db 241    ; Soft only. Volume: 14. Volume only.

    db 241    ; Soft only. Volume: 14. Volume only.

    db 241    ; Soft only. Volume: 14. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

Instrument4_Loop
    db 225    ; Soft only. Volume: 12. Volume only.

    db 7    ; Loop.
DisarkWordForceReference30
    dw Instrument4_Loop    ; Loop here.

Instrument5
    db 1    ; The speed (>0, 0 for 256).

    db 121    ; Soft only. Volume: 15.
    db 147    ; Additional data. Noise: 19. Pitch? false. Arp? false. Period? true.
    dw 1607    ; Forced period.

    db 105    ; Soft only. Volume: 13.
    db 151    ; Additional data. Noise: 23. Pitch? false. Arp? false. Period? true.
    dw 2025    ; Forced period.

    db 105    ; Soft only. Volume: 13.
    db 159    ; Additional data. Noise: 31. Pitch? false. Arp? false. Period? true.
    dw 3214    ; Forced period.

    db 97    ; Soft only. Volume: 12.
    db 159    ; Additional data. Noise: 31. Pitch? false. Arp? false. Period? true.
    dw 3214    ; Forced period.

    db 89    ; Soft only. Volume: 11.
    db 135    ; Additional data. Noise: 7. Pitch? false. Arp? false. Period? true.
    dw 804    ; Forced period.

    db 81    ; Soft only. Volume: 10.
    db 135    ; Additional data. Noise: 7. Pitch? false. Arp? false. Period? true.
    dw 804    ; Forced period.

    db 73    ; Soft only. Volume: 9.
    db 159    ; Additional data. Noise: 31. Pitch? false. Arp? false. Period? true.
    dw 3214    ; Forced period.

    db 65    ; Soft only. Volume: 8.
    db 135    ; Additional data. Noise: 7. Pitch? false. Arp? false. Period? true.
    dw 804    ; Forced period.

    db 57    ; Soft only. Volume: 7.
    db 135    ; Additional data. Noise: 7. Pitch? false. Arp? false. Period? true.
    dw 804    ; Forced period.

    db 49    ; Soft only. Volume: 6.
    db 159    ; Additional data. Noise: 31. Pitch? false. Arp? false. Period? true.
    dw 3214    ; Forced period.

    db 41    ; Soft only. Volume: 5.
    db 135    ; Additional data. Noise: 7. Pitch? false. Arp? false. Period? true.
    dw 804    ; Forced period.

    db 33    ; Soft only. Volume: 4.
    db 135    ; Additional data. Noise: 7. Pitch? false. Arp? false. Period? true.
    dw 804    ; Forced period.

    db 6    ; Loop to silence.

Instrument6
    db 1    ; The speed (>0, 0 for 256).

    db 249    ; Soft only. Volume: 15. Volume only.

    db 241    ; Soft only. Volume: 14. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 217    ; Soft only. Volume: 11. Volume only.

    db 201    ; Soft only. Volume: 9. Volume only.

    db 185    ; Soft only. Volume: 7. Volume only.

    db 169    ; Soft only. Volume: 5. Volume only.

    db 153    ; Soft only. Volume: 3. Volume only.

    db 137    ; Soft only. Volume: 1. Volume only.

    db 6    ; Loop to silence.


; The indexes of the effect blocks used by this song.
EffectBlockTable
DisarkPointerRegionStart31
    dw EffectBlock_P14P32P0    ; Index 0
    dw EffectBlock_P4P0    ; Index 1
    dw EffectBlock_P5P0P11P0P6P0    ; Index 2
    dw EffectBlock_P11P0P6P0    ; Index 3
    dw EffectBlock_P14P16P0    ; Index 4
    dw EffectBlock_P5P0P6P1    ; Index 5
    dw EffectBlock_P0    ; Index 6
DisarkPointerRegionEnd31
EffectBlock_P11P0P6P0
    db 11
    db 0
    db 6
    db 0

EffectBlock_P5P0P6P1
    db 5
    db 0
    db 6
    db 1

EffectBlock_P14P16P0
    db 14
    db 16
    db 0

EffectBlock_P4P0
    db 4
    db 0

EffectBlock_P14P32P0
    db 14
    db 32
    db 0

EffectBlock_P5P0P11P0P6P0
    db 5
    db 0
    db 11
    db 0
    db 6
    db 0

EffectBlock_P0
    db 0


DisarkByteRegionEnd0

; Subsong 0
; ----------------------
Subsong0_DisarkByteRegionStart0
Subsong0_Start
    db 2    ; ReplayFrequency (0=12.5hz, 1=25hz, 2=50hz, 3=100hz, 4=150hz, 5=300hz).
    db 0    ; Digichannel (>=0).
    db 1    ; PSG count (>0).
    db 0    ; Loop start index (>=0).
    db 15    ; End index (>=0).
    db 6    ; Initial speed (>=0).
    db 7    ; Base note index (>=0).

Subsong0_Linker
Subsong0_DisarkPointerRegionStart1
; Position 0
Subsong0_Linker_Loop
    dw Subsong0_Track0
    dw Subsong0_Track1
    dw Subsong0_Track2
    dw Subsong0_LinkerBlock0
; Position 1
    dw Subsong0_Track0
    dw Subsong0_Track1
    dw Subsong0_Track2
    dw Subsong0_LinkerBlock0
; Position 2
    dw Subsong0_Track3
    dw Subsong0_Track4
    dw Subsong0_Track5
    dw Subsong0_LinkerBlock0
; Position 3
    dw Subsong0_Track6
    dw Subsong0_Track1
    dw Subsong0_Track2
    dw Subsong0_LinkerBlock0
; Position 4
    dw Subsong0_Track7
    dw Subsong0_Track1
    dw Subsong0_Track2
    dw Subsong0_LinkerBlock0
; Position 5
    dw Subsong0_Track8
    dw Subsong0_Track1
    dw Subsong0_Track2
    dw Subsong0_LinkerBlock0
; Position 6
    dw Subsong0_Track9
    dw Subsong0_Track10
    dw Subsong0_Track2
    dw Subsong0_LinkerBlock0
; Position 7
    dw Subsong0_Track7
    dw Subsong0_Track0
    dw Subsong0_Track2
    dw Subsong0_LinkerBlock1
; Position 8
    dw Subsong0_Track11
    dw Subsong0_Track0
    dw Subsong0_Track2
    dw Subsong0_LinkerBlock0
; Position 9
    dw Subsong0_Track11
    dw Subsong0_Track0
    dw Subsong0_Track2
    dw Subsong0_LinkerBlock0
; Position 10
    dw Subsong0_Track11
    dw Subsong0_Track9
    dw Subsong0_Track2
    dw Subsong0_LinkerBlock0
; Position 11
    dw Subsong0_Track11
    dw Subsong0_Track9
    dw Subsong0_Track2
    dw Subsong0_LinkerBlock0
; Position 12
    dw Subsong0_Track11
    dw Subsong0_Track8
    dw Subsong0_Track2
    dw Subsong0_LinkerBlock0
; Position 13
    dw Subsong0_Track0
    dw Subsong0_Track9
    dw Subsong0_Track2
    dw Subsong0_LinkerBlock0
; Position 14
    dw Subsong0_Track0
    dw Subsong0_Track12
    dw Subsong0_Track2
    dw Subsong0_LinkerBlock0
; Position 15
    dw Subsong0_Track0
    dw Subsong0_Track13
    dw Subsong0_Track2
    dw Subsong0_LinkerBlock1
Subsong0_DisarkPointerRegionEnd1
    dw 0    ; Loop.
Subsong0_DisarkWordForceReference2
    dw Subsong0_Linker_Loop

Subsong0_LinkerBlock0
    db 64    ; Height.
    db 0    ; Transposition 0.
    db 0    ; Transposition 1.
    db 0    ; Transposition 2.
Subsong0_DisarkWordForceReference3
    dw Subsong0_SpeedTrack0    ; SpeedTrack address.
Subsong0_DisarkWordForceReference4
    dw Subsong0_EventTrack0    ; EventTrack address.

Subsong0_LinkerBlock1
    db 80    ; Height.
    db 0    ; Transposition 0.
    db 0    ; Transposition 1.
    db 0    ; Transposition 2.
Subsong0_DisarkWordForceReference5
    dw Subsong0_SpeedTrack0    ; SpeedTrack address.
Subsong0_DisarkWordForceReference6
    dw Subsong0_EventTrack0    ; EventTrack address.


Subsong0_Track0
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 242
    db 1    ; New Instrument (1).
    db 3    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 48
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 43
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 50
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 48
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 43
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 51
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 50
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 46
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 51
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 50
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 46
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track1
    db 238
    db 2    ; New Instrument (2).
    db 5    ; Index to an effect block.
    db 61
    db 22    ; Waits for 23 lines.

    db 124    ; No note, but effects.
    db 4    ; Index to an effect block.
    db 61
    db 6    ; Waits for 7 lines.

    db 103
    db 1    ; Index to an effect block.
    db 61
    db 22    ; Waits for 23 lines.

    db 124    ; No note, but effects.
    db 4    ; Index to an effect block.
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track2
    db 240
    db 1    ; New Instrument (1).
    db 3    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 46
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 41
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 48
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 46
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 41
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 50
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 48
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 43
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 50
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 48
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 43
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track3
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 242
    db 1    ; New Instrument (1).
    db 3    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 48
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 43
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 50
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 48
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 43
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track4
    db 238
    db 2    ; New Instrument (2).
    db 5    ; Index to an effect block.
    db 61
    db 22    ; Waits for 23 lines.

    db 124    ; No note, but effects.
    db 4    ; Index to an effect block.
    db 61
    db 6    ; Waits for 7 lines.

    db 103
    db 1    ; Index to an effect block.
    db 61
    db 14    ; Waits for 15 lines.

    db 41
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track5
    db 240
    db 1    ; New Instrument (1).
    db 3    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 46
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 41
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 48
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 46
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 41
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track6
    db 238
    db 3    ; New Instrument (3).
    db 3    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 0    ; Index to an effect block.
    db 61
    db 8    ; Waits for 9 lines.

    db 109
    db 1    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 0    ; Index to an effect block.
    db 61
    db 8    ; Waits for 9 lines.

    db 107
    db 1    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 0    ; Index to an effect block.
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track7
    db 238
    db 3    ; New Instrument (3).
    db 2    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 0    ; Index to an effect block.
    db 61
    db 8    ; Waits for 9 lines.

    db 109
    db 1    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 0    ; Index to an effect block.
    db 61
    db 8    ; Waits for 9 lines.

    db 110
    db 1    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 0    ; Index to an effect block.
    db 61
    db 8    ; Waits for 9 lines.

    db 107
    db 1    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 0    ; Index to an effect block.
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track8
    db 238
    db 3    ; New Instrument (3).
    db 2    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 0    ; Index to an effect block.
    db 61
    db 8    ; Waits for 9 lines.

    db 114
    db 1    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 0    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 117
    db 1    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 247
    db 4    ; New Instrument (4).
    db 1    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 0    ; Index to an effect block.
    db 61
    db 18    ; Waits for 19 lines.

    db 242
    db 3    ; New Instrument (3).
    db 1    ; Index to an effect block.
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 124    ; No note, but effects.
    db 4    ; Index to an effect block.
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track9
    db 238
    db 3    ; New Instrument (3).
    db 2    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 0    ; Index to an effect block.
    db 61
    db 8    ; Waits for 9 lines.

    db 109
    db 1    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 0    ; Index to an effect block.
    db 61
    db 8    ; Waits for 9 lines.

    db 107
    db 1    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 0    ; Index to an effect block.
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track10
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 242
    db 1    ; New Instrument (1).
    db 2    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 48
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 43
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 50
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 48
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 43
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 51
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 50
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 46
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 51
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 50
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 46
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track11
    db 214
    db 6    ; New Instrument (6).
    db 6    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 174
    db 5    ; New Instrument (5).
    db 60    ; Waits for 1 line.

    db 150
    db 6    ; New Instrument (6).
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 22
    db 60    ; Waits for 1 line.

    db 174
    db 5    ; New Instrument (5).
    db 60    ; Waits for 1 line.

    db 150
    db 6    ; New Instrument (6).
    db 60    ; Waits for 1 line.

    db 19
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 174
    db 5    ; New Instrument (5).
    db 60    ; Waits for 1 line.

    db 147
    db 6    ; New Instrument (6).
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 19
    db 60    ; Waits for 1 line.

    db 174
    db 5    ; New Instrument (5).
    db 60    ; Waits for 1 line.

    db 147
    db 6    ; New Instrument (6).
    db 60    ; Waits for 1 line.

    db 24
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 174
    db 5    ; New Instrument (5).
    db 60    ; Waits for 1 line.

    db 152
    db 6    ; New Instrument (6).
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 24
    db 60    ; Waits for 1 line.

    db 174
    db 5    ; New Instrument (5).
    db 60    ; Waits for 1 line.

    db 152
    db 6    ; New Instrument (6).
    db 60    ; Waits for 1 line.

    db 17
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 174
    db 5    ; New Instrument (5).
    db 60    ; Waits for 1 line.

    db 145
    db 6    ; New Instrument (6).
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 17
    db 60    ; Waits for 1 line.

    db 174
    db 5    ; New Instrument (5).
    db 60    ; Waits for 1 line.

    db 145
    db 6    ; New Instrument (6).
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track12
    db 238
    db 3    ; New Instrument (3).
    db 2    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 0    ; Index to an effect block.
    db 61
    db 8    ; Waits for 9 lines.

    db 109
    db 1    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 0    ; Index to an effect block.
    db 61
    db 8    ; Waits for 9 lines.

    db 107
    db 1    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 0    ; Index to an effect block.
    db 61
    db 8    ; Waits for 9 lines.

    db 110
    db 1    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 0    ; Index to an effect block.
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track13
    db 61
    db 127    ; Waits for 128 lines.


; The speed tracks
Subsong0_SpeedTrack0
    db 255    ; Wait for 128 lines.

; The event tracks
Subsong0_EventTrack0
    db 255    ; Wait for 128 lines.

Subsong0_DisarkByteRegionEnd0
