;; "_x" values are duplicated colours
ink_white		equ #40
ink_white_x		equ #41
ink_sea_green		equ #42
ink_pastel_yellow	equ #43
ink_blue		equ #44
ink_purple		equ #45
ink_cyan		equ #46
ink_pink		equ #47
ink_purple_x		equ #48
ink_pastel_yellow_x	equ #49
ink_bright_yellow	equ #4a
ink_bright_white	equ #4b
ink_bright_red		equ #4c
ink_bright_magenta	equ #4d
ink_orange		equ #4e
ink_pastel_magenta	equ #4f
ink_blue_x		equ #50
ink_sea_green_x		equ #51
ink_bright_green	equ #52
ink_bright_cyan		equ #53
ink_black		equ #54
ink_bright_blue		equ #55
ink_green		equ #56
ink_sky_blue		equ #57
ink_magenta		equ #58
ink_pastel_green	equ #59
ink_lime		equ #5a
ink_pastel_cyan		equ #5b
ink_red			equ #5c
ink_mauve		equ #5d
ink_yellow		equ #5e
ink_pastel_blue		equ #5f
